apiVersion: apps/v1
kind: Deployment
metadata:
  name: student4-deployment
  namespace: student4
spec:
  selector:
    matchLabels:
      app: student4
  template:
    metadata:
      labels:
        app: student4
    spec:
      containers:
      - name: student4
        image: registry.tanzu.dk/ops2devops/student4:v2
